[package]
name = "canopen"
version = "0.1.0"
authors = ["Dimitri Polonski <dimi.polonski@gmail.com>"]
edition = "2021"
keywords = ["embedded-hal"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-can = "0.3.0"

